jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Mengunduh kode dari repositori GitHub ke server runner
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Menyiapkan lingkungan PHP di server runner
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0' # <-- Ganti ini jika versi PHP Anda bukan 8.2
          extensions: mbstring, xml, ctype, iconv, intl, pdo, bcmath, zip

      # Menginstal package PHP berdasarkan composer.json yang sudah di-checkout
      - name: Install Dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
